config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'articles/index'
  get 'articles/show'
  get 'articles/new'
  get 'clients/index'
  devise_for :users
  root to: 'pages#home'

  namespace :user do
    resources :articles, only: [:index] do
    end
    resources :events, only: [:index, :show] do
      member do
        patch :complete
      end
    end
  end

 resources :events do
  collection do
    get :who
  end
 end

 resources :articles
 resources :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  validates :title, :text, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name, :gender, :birthdate, :email, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :start_date, :end_date, :title, :description, :address, :kind, :link, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :clients, dependent: :destroy
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

   def new
    @article = Article.new # needed to instantiate the form_for
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.save!
    redirect_to user_articles_path
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    # no need for app/views/articles/destroy.html.erb
    redirect_to user_articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :description, :photo)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :who]
  def index
    @eventsall = Event.all

    @events = Event.geocoded
      @markers = @events.map do |event|
        {
          lat: event.latitude,
          lng: event.longitude
        }
      end
  end

  def show
    @event = Event.find(params[:id])
  end
  def who
  end

  def new
    @event = Event.new # needed to instantiate the form_for
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.save!
    redirect_to user_events_path
  end

  def edit

  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    if @event.save
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_events_path
  end

  def complete
    @event = Event.find(params[:id])
    @event.update(status: "complete")
    redirect_to user_events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :price, :address, :start_date, :end_date, :link, :start_time, :end_time, :kind)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @eventsall = Event.all
    @eventsthird = @eventsall.
      where('events.start_date >= ?', Date.today).
      order("events.start_date").
      first(3)
  end
end

app/controllers/user/articles_controller.rb
class User::ArticlesController < ApplicationController
  def index
    @user = current_user
    @articles = current_user.articles
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < ApplicationController
  def index
    @user = current_user
    @events = current_user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="all-index-articles p-5">
  <h1 class= "pb-3">Les actualités</h1>
  <div class="list-index">
    <% @articles.each do |article| %>
      <%= link_to article_path(article), class: "lien-show-article" do %>
        <div class="list-article bg-white my-3">
          <div class="d-flex">
            <div class="col-md-2 p-0">
              <%= cl_image_tag article.photo.key, crop: :thumb, width: 200, height: 150%>

            </div>
            <div class="col-md-8 py-3">
              <div class="title-text-article">
                <h2><%= article.title %></h2>
                <p><%= article.description %></p>

              </div>
            </div>
            <div class="col-md-2 py-3">
              <p>publié le <%= l(article.created_at,format: '%d %B %Y') %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="all-form-article p-5">
  <div class="container article-form">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="form-post mb-5">
          <h1 class="mt-3 mb-5">Créer un article</h1>
          <%= simple_form_for @article do |f| %>
            <%= f.input :title,
                        as: :string,
                        label: 'Titre',
                        placeholder: 'Titre de l\'article' %>
            <%= f.input :description,
                        as: :string,
                        label: 'description',
                        placeholder: "Ajouter une description à l'article" %>
            <%= f.input :text,
                        as: :text,
                        label: 'Texte',
                        placeholder: "Ajouter un texte à l'article" %>

            <%= f.input :photo, as: :file %>

            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Créer", class: 'pho-btn' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="all-article p-5 m-0">
  <div class="container-show-article bg-white">
    <h1 class="p-4"><%= @article.title %></h1>
    <div class="d-flex bg-white">
      <div class="photo-show-article px-4 pb-5">
        <%= cl_image_tag @article.photo.key, crop: :thumb, width: 500, height: 500 %>

        <p>publié le <%= l(@article.created_at, format: '%d %B %Y') %> - écrit par <%= @article.user.first_name %></p>
      </div>
      <div class="text-show-article px-4 pb-5">
        <p><%= @article.text %></p>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="all-clients">
  <div class="client-index">
    <h1 class="ml-5 pt-4">Liste des abonnés</h1>
    <div class="list-clients-newsletter m-5">
      <% @clients.each do |client| %>
        <div class="info-client m-1 p-2">
          <div class="d-flex">
            <div class="col-md-3">
              <div class="d-flex">
                <h2 class="pl-3"><%= client.first_name %></h2>
                <h2 class="pl-3"><%= client.last_name %></h2>
              </div>
            </div>
            <div class="col-md-3">
              <p><%= client.email %></p>
            </div>
            <div class="col-md-2">
              <p><%= l(client.birthdate, format: '%d %B %Y') %></p>
            </div>
            <div class="col-md-2">
              <p><%= client.gender %></p>
            </div>
            <div class="col-md-2">
            <p><%= l(client.created_at, format: '%d %B %Y')%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="d-flex all-index-events">
  <div class="index-left py-5">
    <% if @eventsall.count == 0 %>
      <h1 class="title-index-page pl-5 mb-5">Les évènements</h1>
      <p class="title-index-page">Il n'y a pas d'évènement actuellement.</p>
    <% else %>
      <div class="nom">
        <h1 class="title-index-page pl-5 mb-5">Les évènements</h1>
        <div class="d-flex">
          <div class="row w-100 px-5">
            <% @eventsall.each do |event| %>
            <% if event.start_date > Date.today %>
              <%= link_to event_path(event), class: "link-to-show" do  %>
                <div class="card-event-index mx-3 mb-4">
                  <% if event.kind == "Soirée" %>
                    <%= image_tag("photo-event-party.jpg", crop: :thumb, class: "photo-event") %>
                  <% else %>
                    <%= image_tag("photo-event-other.jpg", crop: :thumb, class: "photo-event") %>
                  <% end %>
                  <div class="info-card-event">
                    <h3 class="text-center pt-2"><%= event.title %></h3>
                    <div class="address-event d-flex">
                      <i class="fas fa-map-marker-alt px-2 pt-2"></i><p class="m-gray"><%= event.address %></p>
                    </div>
                    <div class="date-event">
                      <% if event.start_date == event.end_date %>
                        <div class="d-flex">
                          <i class="fas fa-calendar-alt pt-2 pl-2"></i>
                          <p class="pl-2"><%= l(event.start_date, format: '%d %B %Y') %></p>
                        </div>
                      <% else %>
                        <div class="d-flex">
                          <i class="fas fa-calendar-alt pt-2 pl-2"></i>
                          <p class="pl-2"><%= l(event.start_date, format: '%d %B') %> - <%= l(event.end_date, format: '%d %B %Y') %></p>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
              <% end %>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>

  </div>
    <div class="index-right pt-4">
      <div
        id="map"
        style="width: 450px;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
</div>

app/views/events/new.html.erb
<div class="all-form-event p-5">
  <div class="container event-form">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="form-post mb-5">
          <h1 class="mt-3 mb-5">Créer un évènement</h1>
          <%= simple_form_for @event do |f| %>
            <%= f.input :title,
                        as: :string,
                        label: 'Titre',
                        placeholder: 'Titre de l\'évènement' %>

            <%= f.input :kind,
                        as: :radio_buttons,
                        label: "Type d'évènement :",
                        collection: ['Soirée', 'Autre'],
                        placeholder: 'Titre de l\'évènement' %>

            <%= f.input :address,
                        as: :string,
                        input_html: {id: "autocomplete-location-1"},
                        label: 'Adresse',
                        placeholder: "Indiquer l'adresse de l'évènement" %>

            <%= f.input :description,
                        as: :text,
                        label: 'Description',
                        placeholder: "Ajouter une description à l'évènement" %>

            <%= f.input :price,
                        as: :integer,
                        label: 'Prix',
                        placeholder: "Ajouter le prix de l'évènement" %>
            <%= f.input :link,
                        as: :string,
                        label: 'URL inscription',
                        placeholder: "Ajouter le lien vers le site d'inscription" %>


            <div class="row">
              <div class="start-date col">
                <%= f.input :start_date,
                            as: :date,
                            required: false,
                            input_html: {class: "datepicker"},
                            label: 'Date de début' %>
              </div>
              <div class="end-date col">
                <%= f.input :end_date,
                            as: :date,
                            required: false,
                            input_html: {id: "end_date", class: "end_date"},
                            label: 'Date de fin' %>
              </div>
            </div>
            <div class="row">
              <div class="start_time col">
              <%= f.input :start_time,
                            as: :time,
                            required: false,
                            input_html: {class: "datepicker"},
                            label: 'Heure de début' %>
              </div>
              <div class="end_time col">
              <%= f.input :end_time,
                            as: :time,
                            required: false,
                            input_html: {class: "datepicker"},
                            label: 'Heure de fin' %>
              </div>
            </div>
            <div class="d-flex flex-row-reverse mt-4">
              <%= f.submit "Créer", class: 'pho-btn' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="show-event">
  <div class="container-wrap">
    <h1 class="pl-5 py-4"><%= @event.title %></h1>
    <div class="d-flex">
      <div class="col-md-5">
        <% if @event.kind == "Soirée" %>
          <div class="photo-event-show">
            <%= image_tag("photo-event-party.jpg", crop: :thumb, class: "photo-show-event mx-3") %>
          </div>
        <% else %>
        <div class="photo-event-show">
          <%= image_tag("photo-event-other.jpg", crop: :fill, class: "photo-show-event mx-3") %>
        </div>
        <% end %>
      </div>
      <div class="col-md-7 pt-3">
        <div class="info-show-event mx-5">
          <p><i class="fas fa-map-marker-alt pr-2 pt-2"></i> <%= @event.address %></p>
          <div class="d-flex">
            <i class="far fa-credit-card pt-2 pr-2"></i>
            <p><%= @event.price %> €</p>
          </div>
          <% if @event.start_date == @event.end_date %>
            <div class="d-flex">
              <i class="fas fa-calendar-alt pt-2 pr-2"></i>
              <p><%= l(@event.start_date, format: '%d %B %Y') %></p>
            </div>
          <% else %>
            <div class="d-flex">
              <i class="fas fa-calendar-alt pt-2 pr-2"></i>
              <p><%= l(@event.start_date, format: '%d %B') %> - <%= l(@event.end_date, format: '%d %B %Y') %></p>
            </div>
          <% end %>
          <div class="d-flex">
            <i class="far fa-clock pt-2 pr-2"></i>
            <p><%= l(@event.start_time, format: '%k : %M') %> - <%= l(@event.end_time, format: '%k : %M') %></p>
          </div>
          <p><%= @event.description %></p>
          <div class="d-flex align-items-center justify-content-center">
            <div class="align-items-center justify-content-center">
            <a class="subscribe-button p-1 mt-4" href="<%= @event.link %>">Je m'inscris</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/who.html.erb
<div class="all-article p-5 m-0">
  <div class="container-show-article bg-white">
    <div class="d-flex bg-white">
      <div class="photo-show-who px-4 py-5">
        <%= image_tag("was-logo-sans-fond.png", crop: :thumb, height: 400, width: 500) %>
      </div>
      <div class="text-show-article px-4 pb-5">
        <h2 class="pt-5">QUI SOMMES-NOUS ?</h2>
        <p class="pl-3">Bienvenue chez We Are Single, le spécialiste de la création et de l’organisation d’<strong>évènements pour célibataires</strong>.
        Nos sorties et soirées se déroulent dans plusieurs villes du grand ouest, afin de vous proposer des événements <strong>au plus proche de chez vous</strong>.
        Notre spécificité : <strong>les soirées dansantes</strong> spécial célibataires !
        Ces événements sont l’occasion rêvée de sortir s’amuser et la possibilité de rencontrer votre moitié.
         D’autres événements sont également organisés dans plusieurs villes : speed-datings, rando-datings, cours de danse et bien d’autres !</p>
        <h2>NOTRE PUBLIC</h2>
        <p class="pl-3">Notre public est constitué de célibataires de <strong>plus de 30 ans</strong>, ayant envie de faire de <strong>« vraies » rencontres</strong>.
        Chaque année, des millions de français célibataires s’inscrivent sur des sites de rencontres.
        Nous souhaitons rendre vos rencontres plus réelles et authentiques.</p>
        <h2>NOTRE ENGAGEMENT</h2>
        <p class="pl-3">Nous avons à coeur de vous proposer des événements vous permettant de faire des rencontres dans une ambiance agréable et conviviale, le tout en étant accessible pour vous.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>We Are Single</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
  <div class="photo-cover d-flex">
    <div class="col-md-6 d-flex align-items-center">
    </div>
    <div class="col-md-6 d-flex align-items-center justify-content-center">
      <div class="catch-phrase-home pl-5">
        <h1 class= "catch-phrase">Recontrez,</h1>
        <h1 class= "catch-phrase">Découvrez,</h1>
        <h1 class= "catch-phrase">Profitez</h1>
      </div>
    </div>
  </div>
  <div class="icone-presentation">
    <div class="d-flex">
      <div class="col-md-3">
        <div class="picto d-flex justify-content-center">
          <i class="fas fa-map-marker-alt picto-position"></i>
        </div>
          <p class="text-center pt-2">Près de chez vous</p>
      </div>
      <div class="col-md-3">
        <div class="picto d-flex justify-content-center">
          <i class="fas fa-venus-mars"></i>
        </div>
          <p class="text-center pt-2">parité homme/femme</p>
      </div>
      <div class="col-md-3">
        <div class="picto d-flex justify-content-center">
          <p class="picto-30">+30</p>
        </div>
          <p class="text-center pt-2">Célibataires de plus de 30 ans</p>
      </div>
      <div class="col-md-3">
        <div class="picto d-flex justify-content-center">
          <i class="fas fa-glass-cheers"></i>
        </div>
          <p class="text-center pt-2">Soirée dansante</p>

      </div>
    </div>
  </div>
  <div class="presentation-was-home-page d-flex my-5">
    <div class="col-md-6">
      <div class="text-presentaion ml-4">
      <h1 class="pl-4 py-3">We Are Single</h1>
        <p class="pl-4">We Are Single, c’est l’organisation d’événements dédiés aux célibataires de plus de 30 ans près de chez vous.
        Découvrez les soirées WAS,  et faites des rencontres dans une ambiance conviviale et festive !
        Faites aussi des rencontres lors de nos autres événements pour célibataires : speed-datings, initiation salsa, randonnées…</p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="photo-presentation">
        <%= image_tag("photo-couple-presentation-was.jpg", crop: :thumb, width: 500, height: 300) %>
      </div>
    </div>
  </div>


  <div class="presentation-soirees-home-page d-flex py-3 my-4">
    <div class="col-md-5">
      <div class="photo-soiree py-4 pl-5">
        <%= image_tag("presentation-soiree.jpg", crop: :thumb, width: 500, height: 300) %>
      </div>
    </div>
    <div class="col-md-7 pr-5">
      <div class="title-presentation-soirees-home-page">
          <h1 class="py-3 px-3">Soirée Spécial Célibataire</h1>
      </div>

      <p class="px-4">Dédiées exclusivement aux plus de 30 ans, les soirées WAS sont un excellent moyen de faire des rencontres et peut-être de trouver l’amour.</p>
        <li class="px-4">Soirée dansante animée</li>
        <li class="px-4">Apéritif dinatoire inclus</li>
        <li class="px-4">Ambiance conviviale avec des jeux pour briser la glace.</li>
        <br>
        <p class= "px-4">L’occasion de rencontrer l’amour ou de faire la fête entre célibataires !</p>
    </div>
  </div>
  <div class="list-events-home-page">
    <h1 class="pb-4 px-5 my-0">Les évènements</h1>
    <div class="container-index-event d-flex row mb-5 ml-4">
      <% if @eventsall.count == 0 %>
        <p class="px-5">Il n'y a pas d'évènement actuellement.</p>
      <% else %>
        <% @eventsthird.each do |event| %>
          <% if event.start_date > Date.today %>
          <div class="col-md-4 col-xl-3">
            <%= link_to event_path(event), class: "link-to-show" do  %>
              <div class="card-event">
                <% if event.kind == "Soirée" %>
                  <%= image_tag("photo-event-party.jpg", crop: :thumb, width: 400, height: 220, class: "photo-event-index") %>
                <% else %>
                  <%= image_tag("photo-event-other.jpg", crop: :fill, width: 400, height: 220, class: "photo-event-index") %>
                <% end %>
                  <div class="info-card-event">
                    <h3 class="text-center"><%= event.title %></h3>
                    <div class="location-event d-flex">
                      <i class="fas fa-map-marker-alt px-2 pt-2"></i><p class="m-0"><%= event.address %></p>
                    </div>
                    <div class="date-event d-flex">
                      <% if event.start_date == event.end_date %>
                        <div class="d-flex">
                          <i class="fas fa-calendar-alt pt-2 pl-2"></i>
                          <p class="pl-2"><%= l(event.start_date, format: '%d %B %Y') %></p>
                        </div>
                      <% else %>
                        <div class="d-flex">
                          <i class="fas fa-calendar-alt pt-2 pl-2"></i>
                          <p class="pl-2"><%= l(event.start_date, format: '%d %B') %> - <%= l(event.end_date, format: '%d %B %Y') %></p>
                        </div>
                      <% end %>
                    </div>
                  </div>
              </div>
            <% end %>
          </div>
          <% end %>
        <% end %>
        <%= link_to events_path, class: "link-to-show" do  %>
          <div class="card-event d-flex align-items-center justify-content-center">
            <div class="display-index-events">
              <p class="px-3 text-center">Afficher la liste des évènements</p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="contact d-flex">
    <p class="text-footer text-center p-2">Nous contacter</p>
    <p class="text-footer text-center p-2">Numéro de téléphone : 0607980768</p>
    <p class="text-footer text-center p-2">adresse e-mail : wearesingle@gmail.com</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to '/', class: "navbar-brand" do %>
    <%= image_tag("was-sans-fond.png", crop: :thumb, width: 250, height: 100) %>
  <% end %>

  <div class="container-navbar w-100" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
            <div class="col-md-3">
              <%= link_to user_events_path, class: "action-navbar" do%>
                <p class="text-center my-2">Les évènements</p>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to user_articles_path, class: "action-navbar" do %>
                <p class="text-center my-2">Les actualités</p>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to clients_path, class: "action-navbar" do %>
                <p class="text-center my-2">Les abonnements</p>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to destroy_user_session_path, method: :delete, class: "action-navbar" do %>
                <p class="text-center my-2">Se Déconnecter</p>
              <% end %>
            </div>
        <% else %>

        <div class="nav-item w-100">
          <div class="d-flex">
          <div class="col-md-4">
            <%= link_to events_path, class: "nav-link text-center" do %>
              <p class="text-center my-2">Les évènements</p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%= link_to articles_path, class: "nav-link text-center" do %>
              <p class="text-center my-2">Les actualités</p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%= link_to who_events_path, class: "nav-link text-center" do %>
            <p class="text-center my-2">Qui sommes-nous? </p>
            <% end %>
          </div>
          </div>
        </div>

      <% end %>
    </ul>
  </div>
</div>

app/views/user/articles/index.html.erb
<div class="all-index-articles p-5">
  <div class="d-flex py-3">
    <div class="col-md-11 px-0">
      <h1>Les actualités</h1>
    </div>
    <div class="col-md-1">
      <%= link_to new_article_path, class: "action-navbar" do %>
        <p class="add-event text-center">+</p>
      <% end %>
    </div>
  </div>
  <div class="list-index-articles">
    <% @articles.each do |article| %>

        <div class="list-article">
          <div class="d-flex">
            <div class="col-md-2 p-0">
              <%= cl_image_tag article.photo.key, crop: :thumb, width: 200, height: 150 %>
            </div>
            <div class="col-md-6">
              <div class="title-text-article py-3">
                <h2><%= article.title %></h2>
                <p><%= article.description %></p>
              </div>
            </div>
            <div class="col-md-2 py-3">
              <p>publié le <%= l(article.created_at,format: '%d %B %Y') %></p>
            </div>
            <div class="col-md-2 d-flex justify-content-center py-2">
              <div class="update-index-event-user">
                <%= link_to user_events_path, class: "list-text-index" do  %>
                  <i class="fas fa-pen p-3"></i>
                <% end %>
              </div>
              <div class="destroy-index-event-user">
                <%= link_to article_path(article), method: 'delete', class: "list-text-index" do %>
                  <i class="fas fa-trash-alt p-3"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/user/events/index.html.erb
<div class="user-index-events">
  <div class="d-flex">
    <div class="col-md-11">
    <h1 class="pl-4">Les évènements</h1>
    </div>
    <div class="col-md-1">
      <%= link_to new_event_path, class: "action-navbar" do %>
        <p class="add-event text-center my-2">+</p>
      <% end %>
    </div>
  </div>
  <div class="container-user-index-events">
    <% @events.each do |event| %>
      <div class="list-user-index-events">
        <div class="d-flex event-list-user-index">
          <div class="col-md-3">
            <%= link_to event_path(event), class: "list-text-index" do %>
              <div class="title-event-user-index">
                <h2 class="pl-3"><%= event.title %></h2>
              </div>
            <% end %>
          </div>
          <div class="col-md-4">
            <div class="date-event-user-index">
              <p><%= l(event.start_date, format: '%d %B %Y') %> - <%= l(event.end_date, format: '%d %B %Y') %></p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="event-address-user-index">
              <p><%= event.address %></p>
            </div>
          </div>
          <div class="col-md-2 d-flex justify-content-center">
            <div class="update-index-event-user">
              <%= link_to edit_event_path(event), class: "list-text-index" do  %>
                <i class="fas fa-pen p-3"></i>
              <% end %>
            </div>
            <div class="destroy-index-event-user">
              <%= link_to event_path(event), method: 'delete', class: "list-text-index" do  %>
                <i class="fas fa-trash-alt p-3"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>